import {
  People,
  Book,
  Buildings2,
  UserTick,
  Profile2User,
} from "iconsax-react";

export const ADMIN_DASHBOARD_CARDS = [
  // {
  //   id: "revenue",
  //   title: "Total Revenue",
  //   value: "",
  //   currency: true,
  //   icon: ChartSquare,
  // },
  // {
  //   id: "sales",
  //   title: "Total Sales from Ads",
  //   value: "",
  //   currency: true,
  //   icon: Book,
  // },
  // {
  //   id: "orders",
  //   title: "Total Catalogue Orders",
  //   value: "",
  //   currency: false,
  //   icon: Setting2,
  // },
  // {
  //   id: "contractor",
  //   title: "Contracting Companies",
  //   value: "",
  //   currency: false,
  //   icon: Buildings2,
  // },
  // {
  //   id: "specialist",
  //   title: "Total Professionals",
  //   value: "",
  //   currency: false,
  //   icon: UserTick,
  // },
  // {
  //   id: "vendor",
  //   title: "Total Vendors",
  //   value: "",
  //   currency: false,
  //   icon: Book,
  // },
  // {
  //   id: "client",
  //   title: "Total Clients",
  //   value: "",
  //   currency: false,
  //   icon: Profile2User,
  // },
  // {
  //   id: "total",
  //   title: "Total Users",
  //   value: "",
  //   currency: false,
  //   icon: People,
  // },
  {
    id: "revenue",
    title: "Total Revenue",
    value: "$92,854",
    currency: true,
    percentage: "+6.32%",
  },
  {
    id: "users",
    title: "Total Users",
    value: "48,789",
    currency: true,
    percentage: "+12.45%",
  },
  {
    id: "sales",
    title: "Total Sales from ads",
    value: "$92,854",
    currency: true,
    percentage: "+6.32%",
  },
  {
    id: "orders",
    title: "Total catalogue orders",
    value: "88,234",
    currency: true,
    percentage: "+2.12%",
  },
];
export const MOCK_DATA = [
  {
    country: "United States",
    flag: "us",
    value: "$84.5K",
    change: "+20%",
    color: "success.main",
  },
  {
    country: "India",
    flag: "in",
    value: "$750",
    change: "+18%",
    color: "success.main",
  },
  {
    country: "China",
    flag: "cn",
    value: "$38.5K",
    change: "+14%",
    color: "error.main",
  },
  {
    country: "France",
    flag: "fr",
    value: "$84.5K",
    change: "+28%",
    color: "success.main",
  },
  {
    country: "Australia",
    flag: "au",
    value: "$78.3K",
    change: "-16%",
    color: "error.main",
  },
  {
    country: "Brazil",
    flag: "br",
    value: "$10.5K",
    change: "+25%",
    color: "success.main",
  },
  {
    country: "UAE",
    flag: "ae",
    value: "$30.5K",
    change: "+25%",
    color: "success.main",
  },
];
export const ADMIN_REVENUE_CARDS = [
  {
    id: "revenue",
    title: "Total Revenue",
    value: "$92,854",
    currency: true,
  },
  {
    id: "sales",
    title: "Total Ad sales",
    value: "$92,854",
    currency: true,
  },
  {
    id: "catalogue",
    title: "Total Catalogue sales",
    value: "$92,854",
    currency: true,
  },
  {
    id: "talent",
    title: "Total Talent sales",
    value: "$92,854",
    currency: true,
  },
];

export const ADMIN_USERS_CARDS = [
  {
    id: "users",
    title: "Total Users",
    value: "$92,854",
    currency: true,
  },
  {
    id: "clients",
    title: "Total clients",
    value: "$92,854",
    currency: true,
  },
  {
    id: "contractors",
    title: "Total Contractors",
    value: "$92,854",
    currency: true,
  },
  {
    id: "specialists",
    title: " Total Specialists",
    value: "$92,854",
    currency: true,
  },
  {
    id: "vendors",
    title: "Total Vendors",
    value: "$92,854",
    currency: true,
  },
];
export const ADMIN_CATALOGUE_CARDS = [
  {
    id: "sales",
    title: " Total Sales",
    value: "$92,854",
    currency: true,
  },
  {
    id: "orders",
    title: "Total Orders",
    value: "$92,854",
    currency: true,
  },
  {
    id: "orders per category",
    title: "Orders per category",
    value: "$92,854",
    currency: true,
  },
  {
    id: "orders per Vendor",
    title: "Orders per Vendor",
    value: "$92,854",
    currency: true,
  },
  {
    id: "orders per market",
    title: "Orders per market",
    value: "$92,854",
    currency: true,
  },
];
export const countryNameToCode = {
  Afghanistan: "af",
  Albania: "al",
  Algeria: "dz",
  Andorra: "ad",
  Angola: "ao",
  AntiguaAndBarbuda: "ag",
  Argentina: "ar",
  Armenia: "am",
  Australia: "au",
  Austria: "at",
  Azerbaijan: "az",
  Bahamas: "bs",
  Bahrain: "bh",
  Bangladesh: "bd",
  Barbados: "bb",
  Belarus: "by",
  Belgium: "be",
  Belize: "bz",
  Benin: "bj",
  Bhutan: "bt",
  Bolivia: "bo",
  BosniaAndHerzegovina: "ba",
  Botswana: "bw",
  Brazil: "br",
  Brunei: "bn",
  Bulgaria: "bg",
  BurkinaFaso: "bf",
  Burundi: "bi",
  CaboVerde: "cv",
  Cambodia: "kh",
  Cameroon: "cm",
  Canada: "ca",
  CentralAfricanRepublic: "cf",
  Chad: "td",
  Chile: "cl",
  China: "cn",
  Colombia: "co",
  Comoros: "km",
  CongoBrazzaville: "cg",
  CongoKinshasa: "cd",
  CostaRica: "cr",
  Croatia: "hr",
  Cuba: "cu",
  Cyprus: "cy",
  Czechia: "cz",
  Denmark: "dk",
  Djibouti: "dj",
  Dominica: "dm",
  DominicanRepublic: "do",
  Ecuador: "ec",
  Egypt: "eg",
  ElSalvador: "sv",
  EquatorialGuinea: "gq",
  Eritrea: "er",
  Estonia: "ee",
  Eswatini: "sz",
  Ethiopia: "et",
  Fiji: "fj",
  Finland: "fi",
  France: "fr",
  Gabon: "ga",
  Gambia: "gm",
  Georgia: "ge",
  Germany: "de",
  Ghana: "gh",
  Greece: "gr",
  Grenada: "gd",
  Guatemala: "gt",
  Guinea: "gn",
  GuineaBissau: "gw",
  Guyana: "gy",
  Haiti: "ht",
  Honduras: "hn",
  Hungary: "hu",
  Iceland: "is",
  India: "in",
  Indonesia: "id",
  Iran: "ir",
  Iraq: "iq",
  Ireland: "ie",
  Israel: "il",
  Italy: "it",
  Jamaica: "jm",
  Japan: "jp",
  Jordan: "jo",
  Kazakhstan: "kz",
  Kenya: "ke",
  Kiribati: "ki",
  KoreaNorth: "kp",
  KoreaSouth: "kr",
  Kosovo: "xk",
  Kuwait: "kw",
  Kyrgyzstan: "kg",
  Laos: "la",
  Latvia: "lv",
  Lebanon: "lb",
  Lesotho: "ls",
  Liberia: "lr",
  Libya: "ly",
  Liechtenstein: "li",
  Lithuania: "lt",
  Luxembourg: "lu",
  Madagascar: "mg",
  Malawi: "mw",
  Malaysia: "my",
  Maldives: "mv",
  Mali: "ml",
  Malta: "mt",
  MarshallIslands: "mh",
  Mauritania: "mr",
  Mauritius: "mu",
  Mexico: "mx",
  Micronesia: "fm",
  Moldova: "md",
  Monaco: "mc",
  Mongolia: "mn",
  Montenegro: "me",
  Morocco: "ma",
  Mozambique: "mz",
  Myanmar: "mm",
  Namibia: "na",
  Nauru: "nr",
  Nepal: "np",
  Netherlands: "nl",
  NewZealand: "nz",
  Nicaragua: "ni",
  Niger: "ne",
  Nigeria: "ng",
  NorthMacedonia: "mk",
  Norway: "no",
  Oman: "om",
  Pakistan: "pk",
  Palau: "pw",
  Palestine: "ps",
  Panama: "pa",
  PapuaNewGuinea: "pg",
  Paraguay: "py",
  Peru: "pe",
  Philippines: "ph",
  Poland: "pl",
  Portugal: "pt",
  Qatar: "qa",
  Romania: "ro",
  Russia: "ru",
  Rwanda: "rw",
  SaintKittsAndNevis: "kn",
  SaintLucia: "lc",
  SaintVincentAndTheGrenadines: "vc",
  Samoa: "ws",
  SanMarino: "sm",
  SaoTomeAndPrincipe: "st",
  SaudiArabia: "sa",
  Senegal: "sn",
  Serbia: "rs",
  Seychelles: "sc",
  SierraLeone: "sl",
  Singapore: "sg",
  Slovakia: "sk",
  Slovenia: "si",
  SolomonIslands: "sb",
  Somalia: "so",
  SouthAfrica: "za",
  SouthSudan: "ss",
  Spain: "es",
  SriLanka: "lk",
  Sudan: "sd",
  Suriname: "sr",
  Sweden: "se",
  Switzerland: "ch",
  Syria: "sy",
  Taiwan: "tw",
  Tajikistan: "tj",
  Tanzania: "tz",
  Thailand: "th",
  TimorLeste: "tl",
  Togo: "tg",
  Tonga: "to",
  TrinidadAndTobago: "tt",
  Tunisia: "tn",
  Turkey: "tr",
  Turkmenistan: "tm",
  Tuvalu: "tv",
  Uganda: "ug",
  Ukraine: "ua",
  UnitedArabEmirates: "ae",
  UnitedKingdom: "gb",
  UnitedStates: "us",
  Uruguay: "uy",
  Uzbekistan: "uz",
  Vanuatu: "vu",
  VaticanCity: "va",
  Venezuela: "ve",
  Vietnam: "vn",
  Yemen: "ye",
  Zambia: "zm",
  Zimbabwe: "zw",
};
